### PR TITLE
Dropdown menu :smile: :rocket:

### PR DESCRIPTION
**Pull request by 1fabiopereira**
Simple dropdown menu
Demo html page dropdown

### CODE REVIEW

**Comment by 1fabiopereira** [comment]
I just initially sending the dropdown demo with a bug and had to do a few more commits to solve, I also added accordion to the project beyond the dropdown. :smile: :sunglasses:

**Comment by ghost** [comment]
@1fabiopereira The **Accordion** looks pretty good, but I wont add the Dropbow feature now.

**Comment by 1fabiopereira** [comment]
Okay, okay, I believe it can improve the dropdown, the accordion is okay?

**Comment by ghost** [comment]
@1fabiopereira Take a look into here: https://github.com/oltmannsdaniel/skeleton-plus/issues/21

**Pull request merged**
